name: Input GitHub CI/CD

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Dependencies including Angular CLI
        run: npm ci

      - name: Build Angular App
        run: npm run build --output-path=dist/input
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: built-app
          path: dist/input

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: built-app
          path: dist/input

      - name: Lint Angular App
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: built-app
          path: dist/input

      - name: Test Angular App
        run: npm run test
